version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hyperblog
    command: "npm run start:watch"
    volumes:
      - ".:/usr/share/nginx/html"
    ports:
      - "8090:8080"